{
  "hash": "eaf01b7c037ce5427e7220193ee522d7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear models\"\nformat: html\n---\n\n\n\n\n\nDesign matrix $X$\n\nEach row represents an individual object, columns corresponding to the variables and their specific values for that object\n\nA regression model may be represented via matrix multiplication as\n\n$$y = X \\beta + \\varepsilon$$\n\nThe simple linear regression model\n\n$$y_i = \\underbrace{\\beta_0 + \\beta_1 x_i}_{X \\beta} + \\varepsilon_i$$\n\nThis model can be represented in matrix form as\n\n$$\n\\underbrace{\\left[\\begin{array}{l}\ny_1 \\\\\ny_2 \\\\\ny_3\n\\end{array}\\right]}_{y}\n=\n\\underbrace{\\left[\\begin{array}{ll}\n1 & x_1 \\\\\n1 & x_2 \\\\\n1 & x_3\n\\end{array}\\right]}_{X}\n\\underbrace{\\left[\\begin{array}{l}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\vphantom{}\n\\end{array}\\right]}_{\\beta}\n+\n\\underbrace{\\left[\\begin{array}{l}\n\\varepsilon_1 \\\\\n\\varepsilon_2 \\\\\n\\varepsilon_3\n\\end{array}\\right]}_{\\epsilon}\n$$\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndf <- read.csv(\"data/classroom.csv\")\n```\n:::\n\n\n\n\n\nUse a linear model to estimate a global intercept for `mathgain`, which is equal to the mean of the variable\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mathgain ~ 1, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mathgain ~ 1, data = df)\n\nCoefficients:\n(Intercept)  \n      57.57  \n```\n\n\n:::\n\n```{.r .cell-code}\nmean(df$mathgain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 57.56639\n```\n\n\n:::\n:::\n\n\n\n\n\nLet look at a subset of the data from `schoolid == 3`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmp <- df |> \n  filter(schoolid == 3) |> \n  mutate(\n    classid = factor(classid)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mathgain ~ classid, data = tmp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mathgain ~ classid, data = tmp)\n\nCoefficients:\n(Intercept)   classid137   classid145   classid228  \n       85.0         20.5         11.0        -14.0  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmp |> \n  group_by(classid) |> \n  summarise(mean_mathgain = mean(mathgain))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"classid\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"mean_mathgain\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"11\",\"2\":\"85.0\"},{\"1\":\"137\",\"2\":\"105.5\"},{\"1\":\"145\",\"2\":\"96.0\"},{\"1\":\"228\",\"2\":\"71.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n\nSo you can see the intercept (85.0) is the mean of `classid == 11`. The mean of `classid == 137` is 105.5, which is 85 + 20.5 (intercept + slope) from the linear model. And so on, mean of `classid == 145` is 96 which is `classid == 11` + 11 (85+11).\n\nIf you want an intercept for each class, put `- 1` in the lm formula\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mathgain ~ classid - 1, data = tmp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mathgain ~ classid - 1, data = tmp)\n\nCoefficients:\n classid11  classid137  classid145  classid228  \n      85.0       105.5        96.0        71.0  \n```\n\n\n:::\n:::\n\n\n\n\n\nBy default, reference group is the first group in a factor\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mathgain ~ classid + mathkind - 1, data = tmp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mathgain ~ classid + mathkind - 1, data = tmp)\n\nCoefficients:\n classid11  classid137  classid145  classid228    mathkind  \n  404.1494    431.5223    435.9090    404.8938     -0.7049  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mathgain ~ classid * mathkind - 1, data = tmp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mathgain ~ classid * mathkind - 1, data = tmp)\n\nCoefficients:\n          classid11           classid137           classid145  \n           187.7939             596.0303             561.1480  \n         classid228             mathkind  classid137:mathkind  \n          1376.9393              -0.2270              -0.8336  \nclassid145:mathkind  classid228:mathkind  \n            -0.7376              -2.5300  \n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}